title: "Angus Henderson's Portfolio"
description: "A website to showcase my projects, research, and more."
baseurl: "" # Leave empty if deploying to https://[username].github.io
url: "https://AngusHendo.github.io"
# theme: jekyll-theme-minimal
remote_theme: "mmistakes/minimal-mistakes@4.26.2"
plugins: jekyll-include-cache